# Generated by Django 4.2.16 on 2026-09-02 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0003_sale_branch_sale_customer_sale_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_phone',
            field=models.CharField(blank=True, help_text='Phone number used for mobile money payment.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction_reference',
            field=models.CharField(blank=True, help_text='Mobile money or bank transaction reference.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('M-PESA', 'M-PESA'), ('TIGO-PESA', 'Tigo Pesa'), ('AIRTEL-MONEY', 'Airtel Money'), ('HALOPESA', 'HaloPesa'), ('MIXX-BY-YAS', 'Mixx by Yas'), ('EZY-PESA', 'EzyPesa'), ('BANK_TRANSFER', 'Bank Transfer')], default='CASH', max_length=50),
        ),
    ]
