# Generated by Django 4.2.16 on 2026-09-08 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('sales', '0004_sale_created_by_sale_payment_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='payments.paymentmethod'),
        ),
    ]
