# Generated by Django 4.2.16 on 2026-09-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_payment_method'),
    ]

    operations = [
    ]
