# Generated by Django 4.2.16 on 2026-09-08 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentmethods', '0002_rename_paymentmeth_is_acti_c45fb6_idx_paymentmethod_active_idx_and_more'),
        ('sales', '0006_fix_payment_method_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='paymentmethods.paymentmethod'),
        ),
    ]
