# Generated by Django 4.2.16 on 2026-09-09 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentmethods', '0001_initial'),  # Adjust if needed
        ('sales', '0007_alter_sale_payment_method'),
    ]

    operations = [
        # Add the payment_method field if it doesn't exist
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='sales',
                to='paymentmethods.paymentmethod',
            ),
        ),
        # Run SQL to ensure the column exists in the database
        migrations.RunSQL(
            sql=[
                """
                ALTER TABLE sales_sale 
                ADD COLUMN IF NOT EXISTS payment_method_id BIGINT(20) NULL
                """,
                """
                ALTER TABLE sales_sale 
                ADD CONSTRAINT IF NOT EXISTS sales_sale_payment_method_id_fk 
                FOREIGN KEY (payment_method_id) 
                REFERENCES paymentmethods_paymentmethod(id) 
                ON DELETE SET NULL
                """,
                """
                CREATE INDEX IF NOT EXISTS sales_sale_payment_method_id 
                ON sales_sale(payment_method_id)
                """,
            ],
            reverse_sql=[
                """
                ALTER TABLE sales_sale 
                DROP FOREIGN KEY IF EXISTS sales_sale_payment_method_id_fk
                """,
                """
                DROP INDEX IF EXISTS sales_sale_payment_method_id 
                ON sales_sale
                """,
                """
                ALTER TABLE sales_sale 
                DROP COLUMN IF EXISTS payment_method_id
                """,
            ],
        ),
    ]