# Generated by Django 4.2.16 on 2026-09-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_add_payment_method_field'),  # Your last migration
    ]

    operations = [
        # Add foreign key constraint
        migrations.RunSQL(
            sql=[
                """
                ALTER TABLE sales_sale 
                ADD CONSTRAINT sales_sale_payment_method_id_fk 
                FOREIGN KEY (payment_method_id) 
                REFERENCES paymentmethods_paymentmethod(id) 
                ON DELETE SET NULL
                """,
                
                # Add index
                """
                CREATE INDEX sales_sale_payment_method_id 
                ON sales_sale(payment_method_id)
                """,
            ],
            reverse_sql=[
                """
                ALTER TABLE sales_sale 
                DROP FOREIGN KEY sales_sale_payment_method_id_fk
                """,
                """
                DROP INDEX sales_sale_payment_method_id 
                ON sales_sale
                """,
            ],
        ),
    ]