# Generated by Django 4.2.16 on 2026-09-08 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentmethods', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentmethod',
            new_name='paymentmethod_active_idx',
            old_name='paymentmeth_is_acti_c45fb6_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentmethod',
            new_name='paymentmethod_type_idx',
            old_name='paymentmeth_payment_ca3d9f_idx',
        ),
    ]
