# Generated by Django 4.2.16 on 2026-09-10 10:40

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paymentmethods', '0002_rename_paymentmeth_is_acti_c45fb6_idx_paymentmethod_active_idx_and_more'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='company',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='paymentmethods.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='supported_methods',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='paymenttransactionlog',
            name='request_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='paymenttransactionlog',
            name='response_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='payments_payment_d03ee0_idx'),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
