# Generated by Django 4.2.16 on 2026-08-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='city',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='company',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='country',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='current_balance',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_type',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='tax_number',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
