# Generated by Django 4.2.16 on 2026-10-10 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stock_unique_together_alter_stock_max_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='new_quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='previous_quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='stock_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(check=models.Q(('reserved_quantity__gte', 0)), name='stock_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(check=models.Q(('min_quantity__gte', 0)), name='stock_min_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(check=models.Q(('max_quantity__gte', 0)), name='stock_max_quantity_nonnegative'),
        ),
    ]
