# Generated by Django 4.2.16 on 2026-08-31 07:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_supplier_alter_category_parent_and_more'),
        ('branches', '0001_initial'),
        ('companies', '0001_initial'),
        ('accounts', '0001_initial'),
        ('purchases', '0003_alter_purchase_company_alter_purchase_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchases', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='received_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
