# Generated by Django 4.2.16 on 2026-10-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_company_alter_branch_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
