# Generated by Django 4.2.16 on 2026-09-04 05:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseattachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expenseattachment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_expense_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensebudget',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_expense_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expense_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_expense_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_recurring_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.expensecategory'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='expenseattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_expense_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensebudget',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='expensebudget',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_budgets', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='expensebudget',
            name='budgeted_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='expensebudget',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_budgets', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='expensebudget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expense_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses', to='expenses.expensecategory'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['created_by'], name='expenses_created_5ca70d_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['updated_by'], name='expenses_updated_8e203e_idx'),
        ),
        migrations.AddIndex(
            model_name='expensebudget',
            index=models.Index(fields=['year', 'period'], name='expense_bud_year_096926_idx'),
        ),
        migrations.AddIndex(
            model_name='expensebudget',
            index=models.Index(fields=['branch'], name='expense_bud_branch__7eea37_idx'),
        ),
        migrations.AddIndex(
            model_name='expensebudget',
            index=models.Index(fields=['category'], name='expense_bud_categor_6fcaba_idx'),
        ),
        migrations.AddIndex(
            model_name='expensebudget',
            index=models.Index(fields=['created_by'], name='expense_bud_created_2004cd_idx'),
        ),
        migrations.AddIndex(
            model_name='expensebudget',
            index=models.Index(fields=['updated_by'], name='expense_bud_updated_b5b917_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringexpense',
            index=models.Index(fields=['branch'], name='recurring_e_branch__107a45_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringexpense',
            index=models.Index(fields=['category'], name='recurring_e_categor_e4c9f8_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringexpense',
            index=models.Index(fields=['created_by'], name='recurring_e_created_64c0e9_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringexpense',
            index=models.Index(fields=['updated_by'], name='recurring_e_updated_5fc90e_idx'),
        ),
    ]
